### ISSUE TITLE
Csound for Android - broken links

### ISSUE THREAD

**Issue by arthunkins** [gogins/csound-android#10] opened 2023-04-05 20:51 UTC
Please check the links in your doc. At least one leads nowhere.

Also, a simple comment: I often use Android without wi-fi active (wi-fi reduces CPU speed, as well as other connections like bluetooth, and perhaps other background running apps).

In any case, Csound complains at bootup about lack of internet connection, with windows of complaint remaining for some time. Any way these messages could be eliminated?

This is but a minor inconvenience. Probably more important is the 10 or more seconds it takes to get Csound up and running. (I wonder if that is related to time searching for an internet connection?) Earlier versions of Android Csound do not have this wait, nor do the "alternative" Android Csounds my son Dave made for me (based on Csound 6.01), and currently hosted on my website (arthunkins.com). Interesting too that the latter "alternatives" do not require a complete Android reboot after a crash back to the "desktop"; they can be rerun right from the desktop (and of course don't contain any internet links).

**Comment by gogins** [comment] 2023-08-23 19:15
The Internet requirement is caused by the "Help" button which links to the manual on csound.com. I can remove the button, package the manual in the .apk file (which would make it much larger, or do nothing.

For now, I am doing nothing and closing this issue.

**Closed as completed by gogins** 2023-08-23 19:15 UTC
